export const GET_TODO_LIST_REQUEST="GET_TODO_LIST_REQUEST"
export const GET_TODO_LIST_SUCCESS="GET_TODO_LIST_SUCCESS"
export const GET_TODO_LIST_FAILURE="GET_TODO_LIST_FAILURE"



export const POST_TODO_LIST_REQUEST="POST_TODO_LIST_REQUEST"
export const POST_TODO_LIST_SUCCESS="POST_TODO_LIST_SUCCESS"
export const POST_TODO_LIST_FAILURE="POST_TODO_LIST_FAILURE"



export const SINGLE_TODO_REQUEST="SINGLE_TODO_REQUEST";
export const SINGLE_TODO_SUCCESS="SINGLE_TODO_SUCCESS"
export const SINGLE_TODO_FAILURE="SINGLE_TODO_FAILURE"


export const DELETE_TODO_REQUEST="DELETE_TODO_REQUEST";
export const DELETE_TODO_SUCCESS="DELETE_TODO_SUCCESS"
export const DELETE_TODO_FAILURE="DELETE_TODO_FAILURE"



export const TOGGLE_TODO_REQUEST="TOGGLE_TODO_REQUEST";
export const TOGGLE_TODO_SUCCESS="TOGGLE_TODO_SUCCESS"
export const TOGGLE_TODO_FAILURE="TOGGLE_TODO_FAILURE"

